In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('dataset.csv')
print(dataset)
X = dataset.iloc[:, 0:13].values
y = dataset.iloc[:, 13].values

     Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06               

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [4]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)

X_train2 = pca.fit_transform(X_train)
X_test2 = pca.transform(X_test)

In [5]:
#PCA before-after
from sklearn.linear_model import LogisticRegression
npca = LogisticRegression(random_state=0)
npca.fit(X_train,y_train)

pca = LogisticRegression(random_state=0)
pca.fit(X_train2,y_train)

y_pred = npca.predict(X_test)
y_pred2 = pca.predict(X_test2)

In [6]:
from sklearn.metrics import confusion_matrix
print('real v with pca')
cm = confusion_matrix(y_test,y_pred)
print(cm)

print('wo pca v with pca')
cm2 = confusion_matrix(y_pred,y_pred2)
print(cm2)

real v with pca
[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
wo pca v with pca
[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]


In [10]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components = 2)

X_train_lda = lda.fit_transform(X_train,y_train)
X_test_lda = lda.transform(X_test)

#lda
lda = LogisticRegression(random_state=0)
lda.fit(X_train_lda,y_train)

y_pred3 = lda.predict(X_test_lda)

print('lda v real')
cm3 = confusion_matrix(y_pred,y_pred3)
print(cm3)


lda v real
[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
