In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("dataset.csv")
print(dataset)

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k


In [3]:
x = dataset.iloc[: , 1:4]
y = dataset.iloc[: , 4:]
print(x)
print(y)

    boy  kilo  yas
0   130    30   10
1   125    36   11
2   135    34   10
3   133    30    9
4   129    38   12
5   180    90   30
6   190    80   25
7   175    90   35
8   177    60   22
9   185   105   33
10  165    55   27
11  155    50   44
12  160    58   39
13  162    59   41
14  167    62   55
15  174    70   47
16  193    90   23
17  187    80   27
18  183    88   28
19  159    40   29
20  164    66   32
21  166    56   42
   cinsiyet
0         e
1         e
2         k
3         k
4         e
5         e
6         e
7         e
8         k
9         e
10        k
11        k
12        k
13        k
14        k
15        e
16        e
17        e
18        e
19        k
20        k
21        k


In [4]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.33, random_state = 1)

In [5]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

In [11]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski')
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)


C:\Users\alper\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [15]:

cm = confusion_matrix(y_test,y_pred)
print(cm)

[[3 1]
 [1 3]]


In [16]:
knn2 = KNeighborsClassifier(n_neighbors=2, metric='minkowski')
knn2.fit(X_train, y_train)
y_pred = knn2.predict(X_test)


C:\Users\alper\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [17]:

cm = confusion_matrix(y_test,y_pred)
print(cm)

[[3 1]
 [1 3]]


In [18]:
knn3 = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
knn3.fit(X_train, y_train)
y_pred = knn3.predict(X_test)


C:\Users\alper\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [19]:

cm = confusion_matrix(y_test,y_pred)
print(cm)

[[2 2]
 [0 4]]


In [20]:
knn4 = KNeighborsClassifier(n_neighbors=1, metric='euclidean')
knn4.fit(X_train, y_train)
y_pred = knn4.predict(X_test)


C:\Users\alper\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [21]:

cm = confusion_matrix(y_test,y_pred)
print(cm)

[[3 1]
 [1 3]]


In [27]:
knn5 = KNeighborsClassifier(n_neighbors=1, metric='minkowski')
knn5.fit(X_train, y_train)
y_pred = knn5.predict(X_test)

C:\Users\alper\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [28]:

cm = confusion_matrix(y_test,y_pred)
print(cm)

[[3 1]
 [1 3]]
